---
  version: '3.4'
  networks:
    net:
  services:
    db:
      image: 'docker.io/bitnami/mariadb:latest'
      environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_USER=admin
        - MARIADB_DATABASE=saloon
        - MARIADB_PASSWORD=pass
      volumes:
        - ./:/bitnami/mariadb
      networks:
        - net

    server:
      tty: true
      image: docker.io/bitnami/laravel:8
      environment:
        - DB_HOST=db
        - DB_USERNAME=admin
        - DB_DATABASE=saloon
        - DB_PASSWORD=pass
      depends_on:
        - db
      ports:
        - 3001:3000
      volumes:
        - ./app:/app
      networks:
        - net
      #privileged: true # Modo privilegiado pode ser necessário para rodar no Windows

    frontend:
      container_name: frontend
      build: ./frontend
      volumes:
        - './frontend:/app'
        - '/app/node_modules'
      ports:
        - 3000:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
      networks:
        - net

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      networks:
        - net
